### ISSUE TITLE
Java Services

### ISSUE THREAD

**Issue by roug11** [roug11/movie-reservation-system#2]

**Comment by gkhelo** [comment]
საკითხის ფარგლებში უნდა შეიქმნას შემდეგი Java სერვისები: User, Theater, Payment. თითოეული სერვისი უნდა იყოს [RESTful API](https://aws.amazon.com/what-is/restful-api/). თითოეულ API-ს უნდა ქონდეს ენდპოინტი `GET /hello`, რომელიც დააბრუნებს სტრინგს `Hello World`. აღნიშნული მეთოდისთვის უნდა დაიწეროს მარტივი Unit ტესტიც.

თითოუელი სერვისი უნდა დაემატოს docker-compose-ში. (კონტეინერის შექმნა Java აპლიკაციისთვის: https://docs.docker.com/language/java/)

**Comment by davidpatsina** [comment]
ქვე თასქები:
-- create simple spring boot project
-- create user theatre payment classes with unimplented methods
-- create controllers for payment, user and theatre. All endpoint returns "hello world"
-- create unit tests
 და დოკერზე არ ვიცით როგორ ვქნათ ჯერ.
