### ISSUE TITLE
C# Services

### ISSUE THREAD

**Issue by roug11** [roug11/movie-reservation-system#3]

**Comment by gkhelo** [comment]
საკითხის ფარგლებში უნდა შეიქმნას შემდეგი C# სერვისები: Movie, Reservation. თითოეული სერვისი უნდა იყოს [RESTful API](https://aws.amazon.com/what-is/restful-api/). თითოეულ API-ს უნდა ქონდეს ენდპოინტი `GET /hello`, რომელიც დააბრუნებს სტრინგს `Hello World`. აღნიშნული მეთოდისთვის უნდა დაიწეროს მარტივი Unit ტესტიც.

თითოუელი სერვისი უნდა დაემატოს docker-compose-ში. (კონტეინერის შექმნა .NET აპლიკაციისთვის: https://docs.docker.com/language/dotnet/)
