### ISSUE TITLE
Docker compose file (data base)

### ISSUE THREAD

**Issue by roug11** [roug11/movie-reservation-system#4]

**Comment by gkhelo** [comment]
საკითხის ფარგლებში უნდა შეიქმნას docker-compose ფაილი და დაემატოს 1 სერვისი მონაცემთა ბაზისთვის. უნდა გამოვიყენოთ PostgreSQL (ოფიციალური ინსტრუქცია: https://www.docker.com/blog/how-to-use-the-postgres-docker-official-image/)

README ფაილში უნდა დაემატოს კონტეინერის გაშვების ინსტრუქცია. ასევე, სასურველია თუ დაემატება ლინკი ან ინსტრუქცია თუ როგორ დავაინსტალიროთ docker-compose ლოკალურად.
